name: Deploy LoutikCLOUD Docs

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Installation des dépendances
        run: pip install -r requirements.txt

      - name: Déclaration de l'enregistrement DNS CNAME
        run: echo "infra-docs.loutik.fr" > docs/CNAME        

      - name: Build et Déploiement vers GitHub Pages
        run: mkdocs gh-deploy --force